Fix incorrect updates from when the automated run was performed

diff --git a/.github/workflows/upgrade-dependencies.yml b/.github/workflows/upgrade-dependencies.yml
--- a/.github/workflows/upgrade-dependencies.yml
+++ b/.github/workflows/upgrade-dependencies.yml
@@ -20,8 +20,7 @@ jobs:
         run: cd core && npx projen upgrade-dependencies
       - name: Build
         id: build
-        run: cd core && npx projen build && echo "conclusion=success" || echo >> "$GITHUB_OUTPUT"
-          "conclusion=failure" >> "$GITHUB_OUTPUT"
+        run: cd core && npx projen build && echo "conclusion=success" >> "$GITHUB_OUTPUT" || echo "conclusion=failure" >> "$GITHUB_OUTPUT"
       - name: Create Patch
         run: |-
           git add .
@@ -50,7 +49,8 @@ jobs:
           name: .upgrade.tmp.patch
           path: ${{ runner.temp }}
       - name: Apply patch
-        run: '[ -s ${{ runner.temp }}/.upgrade.tmp.patch ] && git apply ${{ runner.temp
+        run:
+          '[ -s ${{ runner.temp }}/.upgrade.tmp.patch ] && git apply ${{ runner.temp
           }}/.upgrade.tmp.patch || echo "Empty patch. Skipping."'
       - name: Create Pull Request
         id: create-pr
@@ -86,7 +86,8 @@ jobs:
             *Automatically created by projen via the "upgrade-dependencies" workflow*
       - name: Update status check
         if: steps.create-pr.outputs.pull-request-url != ''
-        run: "curl -i --fail -X POST -H \"Accept: application/vnd.github.v3+json\" -H
+        run:
+          "curl -i --fail -X POST -H \"Accept: application/vnd.github.v3+json\" -H
           \"Authorization: token ${GITHUB_TOKEN}\"
           https://api.github.com/repos/${{ github.repository }}/check-runs -d
           '{\"name\":\"build\",\"head_sha\":\"github-actions/upgrade-dependenci\
